Kuvagalleria: ProfileModel Class Reference
ProfileModel Class Reference
Public Member Functions
changePw ($pw, $uid)
getUserPics ($uid)
Detailed Description
Definition at line 19 of file profilemodel.php.
Member Function Documentation
ProfileModel.changePw ($ pw, $ uid)
Change password.
This function changes password for specific user. public
Parameters:
string $pw
integer $uid
Returns:
boolean
Definition at line 31 of file profilemodel.php.
References Galleria_Model._getConnection().
ProfileModel.getUserPics ($ uid)
Get pictures of user.
This function returns specific user related pictures. public
Parameters:
integer $uid
Returns:
array|boolean
Definition at line 46 of file profilemodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/model/profilemodel.php