Kuvagalleria: Galleria_Auth_Model Class Reference
Galleria_Auth_Model Class Reference
Public Member Functions
logIn ($uname, $pword)
getData ($object)
Protected Member Functions
_getUserData ($username, $password)
_getGroups ($userid)
Detailed Description
Definition at line 19 of file model.php.
Member Function Documentation
Galleria_Auth_Model.logIn ($ uname, $ pword)
Gets user information and reformalize it.
Uses username and password to get user information from database and saves that info in authentication object. public
Parameters:
string $uname
string $pword
Returns:
Galleria_Auth_Object
Definition at line 32 of file model.php.
References _getGroups(), and _getUserData().
Galleria_Auth_Model._getUserData ($ username, $ password) [protected]
Gets user information from database.
This function does the database query and returns database query result. private
Parameters:
string $username
string $password
Returns:
stdClass
Definition at line 54 of file model.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
Referenced by logIn().
Galleria_Auth_Model._getGroups ($ userid) [protected]
Gets groups of user.
This function returns groups of user from database. private
Parameters:
integer $userid
Returns:
array
Definition at line 70 of file model.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
Referenced by getData(), and logIn().
Galleria_Auth_Model.getData ($ object)
Updates object.
This function updates existing auth object with new information from database. public
Parameters:
Galleria_Auth_Object $object
Returns:
Galleria_Auth_Object
Definition at line 92 of file model.php.
References Galleria_Model._getConnection(), and _getGroups().
The documentation for this class was generated from the following file:
/var/www/galleria/data/lib/auth/model.php