Kuvagalleria: Galleria_Model Class Reference
Galleria_Model Class Reference
Protected Member Functions
_getConnection ()
_fetchObjects ($state)
_prepareIn ($values)
Detailed Description
Definition at line 20 of file model.php.
Member Function Documentation
Galleria_Model._getConnection () [protected]
Gives database connetion.
This function gives database connection, the PDO object. private
Returns:
Galleria_Database_Pdo
Definition at line 30 of file model.php.
References Galleria_Database.getPDO().
Referenced by Galleria_Model_Collection._addChangelog(), JsonModel._addNewTag(), JsonModel._deleteEmptyTags(), Galleria_Auth_Model._getGroups(), JsonModel._getTagId(), Galleria_Auth_Model._getUserData(), JsonModel.addCat(), AdminModel.addNewGroup(), AdminModel.addNewUser(), AdminModel.addPicture(), JsonModel.addTag(), JsonModel.addUserInGroup(), JsonModel.changeCat(), JsonModel.changeDesc(), JsonModel.changePg(), ProfileModel.changePw(), JsonModel.changeYear(), ImagesModel.checkPermission(), JsonModel.deleteCat(), JsonModel.deleteGroup(), JsonModel.deletePic(), JsonModel.deletePicTag(), JsonModel.deleteUser(), JsonModel.delUserInGroup(), ImagesModel.fileFound(), BrowseModel.getCategories(), BrowseModel.getCatName(), Galleria_Model_Collection.getCats(), JsonModel.getChangelog(), Galleria_Auth_Model.getData(), AdminModel.getGroups(), Galleria_Model_Collection.getGroups(), JsonModel.getGroupsFromCat(), JsonModel.getGroupsFromUser(), ImagesModel.getImageInfo(), ImagesModel.getImageTags(), IndexModel.getLatestPictures(), JsonModel.getPgs(), TagModel.getPics(), AdminModel.getPics(), BrowseModel.getPictures(), Galleria_Model_Collection.getSearchPictures(), IndexModel.getStats(), TagModel.getTagName(), Galleria_Model_Collection.getTags(), ProfileModel.getUserPics(), AdminModel.getUsers(), JsonModel.groupAdmin(), JsonModel.pictureVisibility(), JsonModel.saveCatGroups(), JsonModel.saveCats(), and JsonModel.userActivity().
Galleria_Model._fetchObjects ($ state) [protected]
Fetch objects.
This function fetches objects and returns object array. private
Parameters:
PDOStatement $state
Returns:
array
Definition at line 43 of file model.php.
Referenced by Galleria_Auth_Model._getGroups(), Galleria_Auth_Model._getUserData(), ImagesModel.fileFound(), BrowseModel.getCategories(), Galleria_Model_Collection.getCats(), JsonModel.getChangelog(), AdminModel.getGroups(), Galleria_Model_Collection.getGroups(), JsonModel.getGroupsFromCat(), JsonModel.getGroupsFromUser(), ImagesModel.getImageTags(), IndexModel.getLatestPictures(), JsonModel.getPgs(), TagModel.getPics(), AdminModel.getPics(), BrowseModel.getPictures(), Galleria_Model_Collection.getSearchPictures(), Galleria_Model_Collection.getTags(), ProfileModel.getUserPics(), and AdminModel.getUsers().
Galleria_Model._prepareIn ($ values) [protected]
Prepare in sentence.
This function adds correct value of ?-marks in line for IN statement. private
Parameters:
array $values
Returns:
string
Definition at line 60 of file model.php.
Referenced by ImagesModel.checkPermission(), BrowseModel.getCategories(), BrowseModel.getCatName(), ImagesModel.getImageInfo(), IndexModel.getLatestPictures(), TagModel.getPics(), BrowseModel.getPictures(), Galleria_Model_Collection.getSearchPictures(), IndexModel.getStats(), and Galleria_Model_Collection.getTags().
The documentation for this class was generated from the following file:
/var/www/galleria/data/lib/model.php