Kuvagalleria: JsonController Class Reference
JsonController Class Reference
Public Member Functions
indexAction ()
getAction ()
postAction ()
before ()
Private Member Functions
_parseCatGroups ($data)
_parseCatsToArray ($cats, $parent=null)
Detailed Description
Definition at line 19 of file jsoncontroller.php.
Member Function Documentation
JsonController.indexAction ()
Index page.
Index page action. Sets up Json index page. public
Definition at line 28 of file jsoncontroller.php.
References Galleria_Controller.getView().
JsonController.getAction ()
Get page.
Get page action. Handles all get requests. public
Definition at line 48 of file jsoncontroller.php.
References Galleria_Controller._getModel(), Galleria_Element_Category.create(), Galleria_Auth.getObject(), Galleria_Controller.getView(), Galleria_Element_Category.howMany(), Galleria_Auth.isLogged(), and Galleria_Element_Category.jsonFormat().
JsonController.postAction ()
Post page.
Post page action. Handles all post requests. public
Definition at line 116 of file jsoncontroller.php.
References Galleria_Controller._getModel(), _parseCatGroups(), _parseCatsToArray(), Galleria_Image.deleteFiles(), Galleria_Auth.getObject(), Galleria_Controller.getView(), and Galleria_Auth.isLogged().
JsonController.before ()
Do before.
Does these things before any action. Unsets layout rendering. public
Reimplemented from Galleria_Controller.
Definition at line 177 of file jsoncontroller.php.
References Galleria_Controller.getView().
JsonController._parseCatGroups ($ data) [private]
Parse category groups.
This function parses groups for categories. private
Parameters:
string $data
Returns:
array
Definition at line 191 of file jsoncontroller.php.
Referenced by postAction().
JsonController._parseCatsToArray ($ cats, $ parent = null) [private]
Parse Cats 2 Array.
This function parses categories to array. private
Parameters:
array $cats
integer $parent
Returns:
array
Definition at line 209 of file jsoncontroller.php.
Referenced by postAction().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/controller/jsoncontroller.php