Kuvagalleria: BrowseModel Class Reference
BrowseModel Class Reference
Public Member Functions
getPictures ($cid)
getCategories ()
getCatName ($id)
Detailed Description
Definition at line 19 of file browsemodel.php.
Member Function Documentation
BrowseModel.getPictures ($ cid)
Gets pictures.
This function gets pictures data from database. public
Parameters:
integer $cid
Returns:
array
Definition at line 30 of file browsemodel.php.
References Galleria_Model._fetchObjects(), Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
BrowseModel.getCategories ()
Gets categories.
This function get categories data from database. public
Returns:
array
Definition at line 55 of file browsemodel.php.
References Galleria_Model._fetchObjects(), Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
BrowseModel.getCatName ($ id)
Gets name of category.
This function gets name of specified category from database. public
Parameters:
integer $id
Returns:
string
Definition at line 82 of file browsemodel.php.
References Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/model/browsemodel.php