Kuvagalleria: ImagesController Class Reference
ImagesController Class Reference
Public Member Functions
indexAction ()
fileAction ()
Detailed Description
Definition at line 19 of file imagescontroller.php.
Member Function Documentation
ImagesController.indexAction ()
Index page.
Index page action. Sets up Image index page. public
Definition at line 28 of file imagescontroller.php.
References Galleria_Controller._getModel(), and Galleria_Controller.getView().
ImagesController.fileAction ()
File page.
File page action. Sets up Image file page. public
Definition at line 44 of file imagescontroller.php.
References Galleria_Controller._getModel(), Galleria_Image.fileFound(), Galleria_Image.fileNotFound(), Galleria_Image.getData(), Galleria_Image.getFilesize(), Galleria_Controller.getView(), and Galleria_Image.permissionDenied().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/controller/imagescontroller.php