Kuvagalleria: AdminController Class Reference
AdminController Class Reference
Public Member Functions
indexAction ()
usercontrolAction ()
picturecontrolAction ()
before ()
Protected Member Functions
_modifyUsers ($users, $groups)
_modifyGroups ($gid, $groups)
_insertPicture ($picdata)
_imageInfo ($file)
Detailed Description
Definition at line 19 of file admincontroller.php.
Member Function Documentation
AdminController.indexAction ()
Index page.
Index page action. Sets up Admin index page. public
Definition at line 28 of file admincontroller.php.
AdminController.usercontrolAction ()
User control page.
This page handles all user and group related functionality. public
Definition at line 38 of file admincontroller.php.
References Galleria_Controller._getModel(), _modifyUsers(), and Galleria_Controller.getView().
AdminController.picturecontrolAction ()
Picture control page.
This function handles inserted pictures. public
Definition at line 68 of file admincontroller.php.
References Galleria_Controller._getModel(), _insertPicture(), and Galleria_Controller.getView().
AdminController.before ()
Do these before.
This function checks if user has right to be in these pages. public
Returns:
boolean
Reimplemented from Galleria_Controller.
Definition at line 84 of file admincontroller.php.
References Galleria_Auth.getObject(), Galleria_Auth.isLogged(), and Galleria_Controller.setNext().
AdminController._modifyUsers ($ users, $ groups) [protected]
Modify users.
This function formats users. private
Parameters:
array $users
array $groups
Returns:
array
Definition at line 104 of file admincontroller.php.
References _modifyGroups().
Referenced by usercontrolAction().
AdminController._modifyGroups ($ gid, $ groups) [protected]
Modifies groups.
This function formats groups. private
Parameters:
integer $gid
array $groups
Returns:
stdClass
Definition at line 138 of file admincontroller.php.
Referenced by _modifyUsers().
AdminController._insertPicture ($ picdata) [protected]
Insert picture.
This function inserts picture into tmp file. private
Parameters:
array $picdata PATH_DATA_SITE_IMAGES
Definition at line 159 of file admincontroller.php.
References Galleria_Controller._getModel(), _imageInfo(), Galleria_Controller.getView(), and Galleria_Image.transform().
Referenced by picturecontrolAction().
AdminController._imageInfo ($ file) [protected]
Gives image information.
This function gives information about specific image. private
Parameters:
string $file
Returns:
stdClass
Definition at line 184 of file admincontroller.php.
Referenced by _insertPicture().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/controller/admincontroller.php