Kuvagalleria: TagModel Class Reference
TagModel Class Reference
Public Member Functions
getTagName ($tagid)
getPics ($tagid)
Detailed Description
Definition at line 19 of file tagmodel.php.
Member Function Documentation
TagModel.getTagName ($ tagid)
Gives name of tag.
This function gets name of specific tag from database. public
Parameters:
integer $tagid
Returns:
string
Definition at line 30 of file tagmodel.php.
References Galleria_Model._getConnection().
TagModel.getPics ($ tagid)
Gives pictures.
This function gets pictures from database according specified tag id. public
Parameters:
integer $tagid
Returns:
array
Definition at line 46 of file tagmodel.php.
References Galleria_Model._fetchObjects(), Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/model/tagmodel.php