Kuvagalleria: Galleria_Image Class Reference
Galleria_Image Class Reference
Static Public Member Functions
static getData ($id, $size= '')
static getFilesize ($id, $size= '')
static fileNotFound ($size= '')
static permissionDenied ($size= '')
static fileFound ($id)
static transform ()
static deleteFiles ($pid)
Detailed Description
Definition at line 19 of file image.php.
Member Function Documentation
static Galleria_Image.getData ($ id, $ size = '') [static]
Get image data.
This function includes the image data from file and returns it. public
Parameters:
integer $id
string $size
Returns:
string|boolean PATH_DATA_SITE_IMAGES
Definition at line 33 of file image.php.
Referenced by ImagesController.fileAction().
static Galleria_Image.getFilesize ($ id, $ size = '') [static]
Get image filesize.
This function gets image filesize and returns it. public
Parameters:
integer $id
string $size
Returns:
integer PATH_DATA_SITE_IMAGES
Definition at line 49 of file image.php.
Referenced by ImagesController.fileAction().
static Galleria_Image.fileNotFound ($ size = '') [static]
Get 404 image data.
This function includes the 404 image data from file and returns it. public
Parameters:
string $size
Returns:
string|boolean PATH_DATA_SITE_IMAGES
Definition at line 64 of file image.php.
Referenced by ImagesController.fileAction().
static Galleria_Image.permissionDenied ($ size = '') [static]
Get 403 image data.
This function includes the 403 image data from file and returns it. public
Parameters:
string $size
Returns:
string|boolean PATH_DATA_SITE_IMAGES
Definition at line 79 of file image.php.
Referenced by ImagesController.fileAction().
static Galleria_Image.fileFound ($ id) [static]
Does file found?
This function checks if file exists. public
Parameters:
integer $id
Returns:
boolean PATH_DATA_SITE_IMAGES
Definition at line 94 of file image.php.
Referenced by ImagesController.fileAction().
static Galleria_Image.transform () [static]
Runs transformation.
This function runs image transrofmation. PATH_DATA_SITE_IMAGES
Definition at line 105 of file image.php.
Referenced by AdminController._insertPicture().
static Galleria_Image.deleteFiles ($ pid) [static]
Delete files.
This function delete files for specific picture id. public
Parameters:
integer $pid PATH_DATA_SITE_IMAGES
Definition at line 120 of file image.php.
Referenced by JsonController.postAction().
The documentation for this class was generated from the following file:
/var/www/galleria/data/lib/image.php