Kuvagalleria: Galleria_Controller Class Reference
Galleria_Controller Class Reference
Public Member Functions
__construct ($action, $model, $requests)
before ()
after ()
getView ()
setNext ($cont, $act)
getPage ()
getSubpage ()
redirect ($cont, $act)
isRedirected ()
Protected Member Functions
_getModel ()
Protected Attributes
$_action
$_model
$_view
$_requests
$_ncont
$_nact
$_redirect
Detailed Description
Definition at line 20 of file controller.php.
Constructor & Destructor Documentation
Galleria_Controller.__construct ($ action, $ model, $ requests)
#@- Creates controller.
This is contructor of Controller. public
Parameters:
string $action
Galleria_Model $model
Galleria_Requests $requests
Definition at line 65 of file controller.php.
Member Function Documentation
Galleria_Controller._getModel () [protected]
Gives model.
This function gives controller related model. private
Returns:
Galleria_Model
Exceptions:
Exception
Definition at line 84 of file controller.php.
Referenced by AdminController._insertPicture(), ImagesController.fileAction(), JsonController.getAction(), TagController.indexAction(), SearchController.indexAction(), ProfileController.indexAction(), IndexController.indexAction(), ImagesController.indexAction(), BrowseController.indexAction(), AdminController.picturecontrolAction(), JsonController.postAction(), and AdminController.usercontrolAction().
Galleria_Controller.before ()
Do before.
These is done before actual action. Returned boolean indicates continuing of controller. public
Returns:
boolean
Reimplemented in AdminController, JsonController, LoginController, and ProfileController.
Definition at line 101 of file controller.php.
Galleria_Controller.after ()
Do after.
These is done after actual action. Returned boolean indicates continuing of controller. public
Returns:
boolean
Definition at line 114 of file controller.php.
Galleria_Controller.getView ()
Gives view.
This function returns the view of controller. public
Returns:
Galleria_View
Definition at line 126 of file controller.php.
Referenced by AdminController._insertPicture(), JsonController.before(), ImagesController.fileAction(), JsonController.getAction(), TagController.indexAction(), SearchController.indexAction(), ProfileController.indexAction(), JsonController.indexAction(), IndexController.indexAction(), ImagesController.indexAction(), BrowseController.indexAction(), AdminController.picturecontrolAction(), JsonController.postAction(), and AdminController.usercontrolAction().
Galleria_Controller.setNext ($ cont, $ act)
Sets next.
This function sets next controller and action, which will be runned. public
Parameters:
string $cont
string $act
Definition at line 139 of file controller.php.
Referenced by ProfileController.before(), AdminController.before(), and redirect().
Galleria_Controller.getPage ()
Gives next controller.
Gives next controller, which will be runned. public
Returns:
string
Definition at line 152 of file controller.php.
Galleria_Controller.getSubpage ()
Gives next controller action.
Gives next controller action, which will be runned. public
Returns:
string
Definition at line 164 of file controller.php.
Galleria_Controller.redirect ($ cont, $ act)
Sets redirection.
This function not just tells next controller and action. It also tells to stop further rendering and jump to totally new page. public
Definition at line 176 of file controller.php.
References setNext().
Galleria_Controller.isRedirected ()
Will redirect?
Tells if redirection is set. public
Returns:
boolean
Definition at line 189 of file controller.php.
Member Data Documentation
Galleria_Controller.$_action [protected]
Definition at line 29 of file controller.php.
Galleria_Controller.$_model [protected]
Definition at line 33 of file controller.php.
Galleria_Controller.$_view [protected]
Definition at line 37 of file controller.php.
Galleria_Controller.$_requests [protected]
Definition at line 41 of file controller.php.
Galleria_Controller.$_ncont [protected]
Definition at line 45 of file controller.php.
Galleria_Controller.$_nact [protected]
Definition at line 49 of file controller.php.
Galleria_Controller.$_redirect [protected]
Definition at line 53 of file controller.php.
The documentation for this class was generated from the following file:
/var/www/galleria/data/lib/controller.php