Kuvagalleria: ProfileController Class Reference
ProfileController Class Reference
Public Member Functions
indexAction ()
before ()
Detailed Description
Definition at line 19 of file profilecontroller.php.
Member Function Documentation
ProfileController.indexAction ()
Profile page.
This gives profile page. public
Definition at line 28 of file profilecontroller.php.
References Galleria_Controller._getModel(), Galleria_Auth.getObject(), and Galleria_Controller.getView().
ProfileController.before ()
Do this before.
This function checks if user is logged in to show his&hre profile. public
Returns:
boolean
Reimplemented from Galleria_Controller.
Definition at line 47 of file profilecontroller.php.
References Galleria_Auth.isLogged(), and Galleria_Controller.setNext().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/controller/profilecontroller.php