Kuvagalleria: IndexModel Class Reference
IndexModel Class Reference
Public Member Functions
getLatestPictures ()
getStats ()
Detailed Description
Definition at line 19 of file indexmodel.php.
Member Function Documentation
IndexModel.getLatestPictures ()
Give latest pictures.
This function gets latest pictures from database. public
Returns:
array
Definition at line 29 of file indexmodel.php.
References Galleria_Model._fetchObjects(), Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
IndexModel.getStats ()
Give stats.
This function gets some site relevate statistics. public
Returns:
stdClass
Definition at line 54 of file indexmodel.php.
References Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/model/indexmodel.php