Kuvagalleria: ImagesModel Class Reference
ImagesModel Class Reference
Public Member Functions
getImageInfo ($pid)
getImageTags ($pid)
fileFound ($pid)
checkPermission ($pid)
Detailed Description
Definition at line 19 of file imagesmodel.php.
Member Function Documentation
ImagesModel.getImageInfo ($ pid)
Gives image info.
This function gets image information from database and returns it. public
Parameters:
integer $pid
Returns:
Galleria_Image_Object
Definition at line 30 of file imagesmodel.php.
References Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
ImagesModel.getImageTags ($ pid)
Gives image tags.
This function gets image related tags from database and retruns them. public
Parameters:
integer $pid
Returns:
array
Definition at line 57 of file imagesmodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
ImagesModel.fileFound ($ pid)
Is file found?
This function checks if file is set in database. public
Parameters:
integer $pid
Returns:
boolean
Definition at line 73 of file imagesmodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
ImagesModel.checkPermission ($ pid)
Check permission.
This function checks if user has permission to see selected picture. public
Parameters:
integer $pid
Returns:
boolean
Definition at line 89 of file imagesmodel.php.
References Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/model/imagesmodel.php