Kuvagalleria: Galleria_Configuration Class Reference
Galleria_Configuration Class Reference
Static Public Member Functions
static set ($configs)
static get ()
Detailed Description
Definition at line 19 of file configuration.php.
Member Function Documentation
static Galleria_Configuration.set ($ configs) [static]
Sets configurations.
Function sets configuration in object and searialize it in session. State of success is returned. public
Parameters:
array $configs
Returns:
boolean
Definition at line 32 of file configuration.php.
References Galleria_Session.set().
Referenced by Galleria_Auto_Configure.configFiles().
static Galleria_Configuration.get () [static]
Gets configurations.
Function gets configuration object from session, unserialize it and gives the configuration object. public
Returns:
Galleria_Configuration_Object
Definition at line 46 of file configuration.php.
References Galleria_Session.get().
The documentation for this class was generated from the following file:
/var/www/galleria/data/lib/configuration.php