Kuvagalleria: BrowseController Class Reference
BrowseController Class Reference
Public Member Functions
indexAction ()
Detailed Description
Definition at line 19 of file browsecontroller.php.
Member Function Documentation
BrowseController.indexAction ()
Index page.
Index page action. Sets up Browse index page. public
Definition at line 28 of file browsecontroller.php.
References Galleria_Controller._getModel(), Galleria_Element_Category.create(), and Galleria_Controller.getView().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/controller/browsecontroller.php