Kuvagalleria: Galleria_Element_Category Class Reference
Galleria_Element_Category Class Reference
Public Member Functions
__construct ($id, $name, $parent=null, $pics=true)
addChild (Galleria_Element_Category $child)
addChildren ($children)
__toString ()
getName ()
getId ()
getParent ()
hasPics ()
getChildren ()
hasChildren ()
getCount ()
Static Public Member Functions
static create ($cats)
static howMany ($element)
static jsonFormat ($element)
Protected Attributes
$_id
$_parent
$_name
$_children
$_pics
Static Private Member Functions
static _appendChildren ($parent, $children)
Detailed Description
Definition at line 19 of file category.php.
Constructor & Destructor Documentation
Galleria_Element_Category.__construct ($ id, $ name, $ parent = null, $ pics = true)
#@- Creates category element.
This is contructor of category element. public
Parameters:
integer $id
string $name
integer $parent
boolean $pics
Definition at line 57 of file category.php.
Member Function Documentation
Galleria_Element_Category.addChild (Galleria_Element_Category $ child)
Add child.
This function adds child to this category. public
Parameters:
Galleria_Element_Category $child
Definition at line 73 of file category.php.
Galleria_Element_Category.addChildren ($ children)
Add children.
This function adds children to this category. public
Parameters:
array $children
Definition at line 85 of file category.php.
Galleria_Element_Category.__toString ()
To string.
This function converts category element to string. public
Returns:
string
Definition at line 97 of file category.php.
References getName().
Galleria_Element_Category.getName ()
Gives name.
This function gives name of category element. public
Returns:
string
Definition at line 109 of file category.php.
Referenced by __toString(), and jsonFormat().
Galleria_Element_Category.getId ()
Gives id.
This function gives id of category element. public
Returns:
integer
Definition at line 121 of file category.php.
Referenced by _appendChildren(), and jsonFormat().
Galleria_Element_Category.getParent ()
Gives parent.
This function gives parent of category element. public
Returns:
integer
Definition at line 133 of file category.php.
Referenced by _appendChildren().
Galleria_Element_Category.hasPics ()
Has pictures?
This function tells if category element has pictures. public
Returns:
boolean
Definition at line 145 of file category.php.
Galleria_Element_Category.getChildren ()
Gives children.
This function gives children of category element. public
Returns:
array
Definition at line 157 of file category.php.
Referenced by getCount(), and jsonFormat().
Galleria_Element_Category.hasChildren ()
Has children?
This function tells if category element has children. public
Returns:
boolean
Definition at line 169 of file category.php.
Referenced by getCount(), and jsonFormat().
Galleria_Element_Category.getCount ()
Count.
This function returns number of category elements following. public
Returns:
integer
Definition at line 181 of file category.php.
References getChildren(), and hasChildren().
static Galleria_Element_Category.create ($ cats) [static]
Creates category element.
This function creates category element tree from list of array. public
Parameters:
array $cats
Returns:
array
Definition at line 201 of file category.php.
Referenced by JsonController.getAction(), and BrowseController.indexAction().
static Galleria_Element_Category._appendChildren ($ parent, $ children) [static, private]
Appends children.
This function appends children for specific category element. private
Parameters:
integer $parent
array $children
Returns:
array
Definition at line 220 of file category.php.
References getId(), and getParent().
static Galleria_Element_Category.howMany ($ element) [static]
How many?
This function tells how many items are in hierarchy. public
Parameters:
array|Galleria_Element_Category $element
Returns:
integer
Definition at line 245 of file category.php.
Referenced by JsonController.getAction().
static Galleria_Element_Category.jsonFormat ($ element) [static]
JSON format.
This function creates specific format for this elements type. public
Parameters:
array|Galleria_Element_Category $element
Returns:
array
Definition at line 266 of file category.php.
References getChildren(), getId(), getName(), and hasChildren().
Referenced by JsonController.getAction().
Member Data Documentation
Galleria_Element_Category.$_id [protected]
Definition at line 28 of file category.php.
Galleria_Element_Category.$_parent [protected]
Definition at line 32 of file category.php.
Galleria_Element_Category.$_name [protected]
Definition at line 36 of file category.php.
Galleria_Element_Category.$_children [protected]
Definition at line 40 of file category.php.
Galleria_Element_Category.$_pics [protected]
Definition at line 44 of file category.php.
The documentation for this class was generated from the following file:
/var/www/galleria/data/lib/element/category.php