Kuvagalleria: Galleria_Model_Collection Class Reference
Galleria_Model_Collection Class Reference
Public Member Functions
getSearchPictures ($text, $pg, $year)
getCats ()
getGroups ()
getTags ()
Protected Member Functions
_addChangelog ($uid, $pid, $action)
Detailed Description
Definition at line 20 of file collection.php.
Member Function Documentation
Galleria_Model_Collection.getSearchPictures ($ text, $ pg, $ year)
Gives searched pictures.
This function gets searched pictures. public
Parameters:
string $text
string $pg
string $year
Returns:
array
Definition at line 33 of file collection.php.
References Galleria_Model._fetchObjects(), Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
Galleria_Model_Collection.getCats ()
Gives categories.
This function returns categories from database. public
Returns:
array
Definition at line 56 of file collection.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
Galleria_Model_Collection.getGroups ()
Gives groups.
This function returns group data from database. public
Returns:
array
Reimplemented in AdminModel.
Definition at line 71 of file collection.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
Galleria_Model_Collection.getTags ()
Gives tags.
This function gets tags from database. public
Returns:
array
Definition at line 86 of file collection.php.
References Galleria_Model._fetchObjects(), Galleria_Model._getConnection(), Galleria_Model._prepareIn(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
Galleria_Model_Collection._addChangelog ($ uid, $ pid, $ action) [protected]
Add to changelog.
This function adds data to changelog of picture. private
Parameters:
integer $uid
integer $pid
string $action
Returns:
boolean
Definition at line 114 of file collection.php.
References Galleria_Model._getConnection().
Referenced by AdminModel.addPicture(), JsonModel.addTag(), JsonModel.changeCat(), JsonModel.changeDesc(), JsonModel.changePg(), JsonModel.changeYear(), JsonModel.deletePicTag(), and JsonModel.pictureVisibility().
The documentation for this class was generated from the following file:
/var/www/galleria/data/lib/model/collection.php