Kuvagalleria: Galleria_Session Class Reference
Galleria_Session Class Reference
Static Public Member Functions
static set ($name, $value)
static get ($name)
static del ($name)
Detailed Description
Definition at line 27 of file session.php.
Member Function Documentation
static Galleria_Session.set ($ name, $ value) [static]
Sets session variable.
This function inserts value for named variable. public
Parameters:
string $name
mixed $value
Returns:
mixed
Definition at line 40 of file session.php.
Referenced by Galleria_Auth.init(), Galleria_Configuration.set(), and Galleria_Auth.tryLog().
static Galleria_Session.get ($ name) [static]
Gets session variable.
This function gives value of session variable. public
Parameters:
string $name
Returns:
mixed
Definition at line 54 of file session.php.
Referenced by Galleria_Configuration.get(), Galleria_Auth.getObject(), and Galleria_Auth.isLogged().
static Galleria_Session.del ($ name) [static]
Deletes session variable.
This function deletes variable from session. public
Parameters:
string $name
Returns:
boolean
Definition at line 68 of file session.php.
Referenced by Galleria_Auth.logOut().
The documentation for this class was generated from the following file:
/var/www/galleria/data/lib/session.php