Kuvagalleria: JsonModel Class Reference
JsonModel Class Reference
Public Member Functions
deleteUser ($uid)
userActivity ($uid, $act)
addUserInGroup ($uid, $gid)
delUserInGroup ($uid, $gid)
getGroupsFromUser ($uid, $involves=true)
saveCatGroups ($groups, $catid)
groupAdmin ($gid, $admin)
deleteGroup ($gid)
saveCats ($cats)
addCat ($name)
deleteCat ($id)
getGroupsFromCat ($cid)
changeDesc ($pid, $text)
changePg ($pid, $text)
changeYear ($pid, $text)
changeCat ($pid, $cid)
addTag ($pid, $name)
pictureVisibility ($pid, $show)
deletePicTag ($pid, $tid)
deletePic ($pid)
getChangelog ($pid)
getPgs ()
Private Member Functions
_catsToSqlString ($cat)
_groupsToSqlString ($catid, $groupid)
_addNewTag ($name)
_getTagId ($name)
_deleteEmptyTags ()
Detailed Description
Definition at line 19 of file jsonmodel.php.
Member Function Documentation
JsonModel.deleteUser ($ uid)
Delete user.
This function deletes user. public
Parameters:
integer $uid
Returns:
boolean
Definition at line 32 of file jsonmodel.php.
References Galleria_Model._getConnection().
JsonModel.userActivity ($ uid, $ act)
Change user activity.
This function grants and removes active status from user. public
Parameters:
integer $uid
boolean $act
Returns:
stdClass
Definition at line 48 of file jsonmodel.php.
References Galleria_Model._getConnection().
JsonModel.addUserInGroup ($ uid, $ gid)
Add user in group.
This function adds user in group. public
Parameters:
integer $uid
integer $gid
Returns:
boolean
Definition at line 67 of file jsonmodel.php.
References Galleria_Model._getConnection().
JsonModel.delUserInGroup ($ uid, $ gid)
Delete user from group.
This function deletes user from group. public
Parameters:
integer $uid
integer $gid
Returns:
boolean
Definition at line 83 of file jsonmodel.php.
References Galleria_Model._getConnection().
JsonModel.getGroupsFromUser ($ uid, $ involves = true)
Give groups form user.
This function returns groups where user is in. public
Parameters:
integer $uid
boolean $involves
Returns:
array
Definition at line 99 of file jsonmodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
JsonModel.saveCatGroups ($ groups, $ catid)
Save category groups.
This function clears and adds new groups for category. public
Parameters:
array $groups
integer $catid
Returns:
boolean
Definition at line 119 of file jsonmodel.php.
References Galleria_Model._getConnection(), and _groupsToSqlString().
JsonModel.groupAdmin ($ gid, $ admin)
Toggle admin status.
This function grants and removes admin status from group. public
Parameters:
integer $gid
boolean $admin
Returns:
stdClass
Definition at line 143 of file jsonmodel.php.
References Galleria_Model._getConnection().
JsonModel.deleteGroup ($ gid)
Delete group.
This function deletes group. public
Parameters:
integer $gid
Returns:
boolean
Definition at line 161 of file jsonmodel.php.
References Galleria_Model._getConnection().
JsonModel.saveCats ($ cats)
Saves categories.
This function saves the categories hierarchy. public
Parameters:
array $cats
Returns:
boolean
Definition at line 178 of file jsonmodel.php.
References _catsToSqlString(), and Galleria_Model._getConnection().
JsonModel.addCat ($ name)
Add category.
This function creates category. public
Parameters:
string $name
Returns:
boolean
Definition at line 199 of file jsonmodel.php.
References Galleria_Model._getConnection().
JsonModel.deleteCat ($ id)
Delete category.
This function deletes category. public
Parameters:
integer $id
Returns:
boolean
Definition at line 214 of file jsonmodel.php.
References Galleria_Model._getConnection().
JsonModel.getGroupsFromCat ($ cid)
Gives category related groups.
This function group data, which is related to specific category id. public
Parameters:
integer $cid
Returns:
array
Definition at line 229 of file jsonmodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
JsonModel._catsToSqlString ($ cat) [private]
Category SQL string.
This function creates SQL string for category update. private
Parameters:
stdClass $cat
Returns:
boolean
Definition at line 245 of file jsonmodel.php.
Referenced by saveCats().
JsonModel._groupsToSqlString ($ catid, $ groupid) [private]
Format category groups.
This function format category id and groups id to categorygroups query. private
Parameters:
integer $catid
integer $groupid return stdClass
Definition at line 262 of file jsonmodel.php.
Referenced by saveCatGroups().
JsonModel.changeDesc ($ pid, $ text)
Change description.
This function changes description of picture. public
Parameters:
integer $pid
string $text
Returns:
boolean
Definition at line 281 of file jsonmodel.php.
References Galleria_Model_Collection._addChangelog(), Galleria_Model._getConnection(), and Galleria_Auth.getObject().
JsonModel.changePg ($ pid, $ text)
Change photographer.
This function changes photographer of picture. public
Parameters:
integer $pid
string $text
Returns:
boolean
Definition at line 297 of file jsonmodel.php.
References Galleria_Model_Collection._addChangelog(), Galleria_Model._getConnection(), and Galleria_Auth.getObject().
JsonModel.changeYear ($ pid, $ text)
Change year.
This function changes year of picture. public
Parameters:
integer $pid
string $text
Returns:
boolean
Definition at line 313 of file jsonmodel.php.
References Galleria_Model_Collection._addChangelog(), Galleria_Model._getConnection(), and Galleria_Auth.getObject().
JsonModel.changeCat ($ pid, $ cid)
Change category.
This function changes category for picture. public
Parameters:
integer $pid
integer $cid
Returns:
boolean
Definition at line 329 of file jsonmodel.php.
References Galleria_Model_Collection._addChangelog(), Galleria_Model._getConnection(), and Galleria_Auth.getObject().
JsonModel.addTag ($ pid, $ name)
Add tag.
This function adds specific named tag to picture and creates tag if it doesn't already exists. public
Parameters:
integer $pid
string $name
Returns:
integer|null
Definition at line 346 of file jsonmodel.php.
References Galleria_Model_Collection._addChangelog(), _addNewTag(), Galleria_Model._getConnection(), _getTagId(), and Galleria_Auth.getObject().
JsonModel._addNewTag ($ name) [private]
Creates new tag.
This function creates tag for specified name of tag. private
Parameters:
string $name
Returns:
integer|null
Definition at line 363 of file jsonmodel.php.
References Galleria_Model._getConnection().
Referenced by addTag().
JsonModel._getTagId ($ name) [private]
Gives tag id.
This function return tag id, which belogns to specific name of tag. private
Parameters:
string $name
Returns:
integer|null
Definition at line 378 of file jsonmodel.php.
References Galleria_Model._getConnection().
Referenced by addTag().
JsonModel.pictureVisibility ($ pid, $ show)
Toggle picture shown.
This function changes picture visibility between shown and hidden. public
Parameters:
integer $pid
boolean $show
Returns:
boolean
Definition at line 394 of file jsonmodel.php.
References Galleria_Model_Collection._addChangelog(), Galleria_Model._getConnection(), and Galleria_Auth.getObject().
JsonModel.deletePicTag ($ pid, $ tid)
Delete picture tag.
This function deletes tag from picture and if there are no relation assigned to tag, it will be removed. public
Parameters:
integer $pid
integer $tid
Returns:
boolean
Definition at line 415 of file jsonmodel.php.
References Galleria_Model_Collection._addChangelog(), _deleteEmptyTags(), Galleria_Model._getConnection(), and Galleria_Auth.getObject().
JsonModel._deleteEmptyTags () [private]
Delete empty tags.
This function deletes empty tags from database. private
Returns:
boolean
Definition at line 437 of file jsonmodel.php.
References Galleria_Model._getConnection().
Referenced by deletePic(), and deletePicTag().
JsonModel.deletePic ($ pid)
Delete picture.
This function deleted picture. public
Parameters:
integer $pid
Returns:
boolean
Definition at line 452 of file jsonmodel.php.
References _deleteEmptyTags(), and Galleria_Model._getConnection().
JsonModel.getChangelog ($ pid)
Gives changelog.
This function returns changelog for specified picture. public
Parameters:
integer $pid
Returns:
array
Definition at line 467 of file jsonmodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
JsonModel.getPgs ()
Gives changelog.
This function returns changelog for specified picture. public
Parameters:
integer $pid
Returns:
array
Definition at line 483 of file jsonmodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/model/jsonmodel.php