Kuvagalleria: Galleria_Auth Class Reference
Galleria_Auth Class Reference
Static Public Member Functions
static tryLog ($username, $password)
static isLogged ()
static getObject ()
static logOut ()
static init ()
Detailed Description
Definition at line 19 of file auth.php.
Member Function Documentation
static Galleria_Auth.tryLog ($ username, $ password) [static]
The logging function.
This is the function, which should be used on logging in. public
Parameters:
string $username
string $password
Definition at line 31 of file auth.php.
References Galleria_Session.set().
static Galleria_Auth.isLogged () [static]
Checks if already logged in.
This function checks if user is already logged in and returns the information. public
Returns:
boolean
Definition at line 50 of file auth.php.
References Galleria_Session.get().
Referenced by ProfileController.before(), LoginController.before(), AdminController.before(), ImagesModel.checkPermission(), JsonController.getAction(), BrowseModel.getCategories(), BrowseModel.getCatName(), ImagesModel.getImageInfo(), IndexModel.getLatestPictures(), TagModel.getPics(), BrowseModel.getPictures(), Galleria_Model_Collection.getSearchPictures(), IndexModel.getStats(), Galleria_Model_Collection.getTags(), Galleria_View_Tags.lists(), and JsonController.postAction().
static Galleria_Auth.getObject () [static]
Gives auth object.
This function returns auth object. public
Returns:
Galleria_Auth_Object
Definition at line 64 of file auth.php.
References Galleria_Session.get().
Referenced by AdminModel.addPicture(), JsonModel.addTag(), AdminController.before(), JsonModel.changeCat(), JsonModel.changeDesc(), JsonModel.changePg(), JsonModel.changeYear(), ImagesModel.checkPermission(), JsonModel.deletePicTag(), JsonController.getAction(), BrowseModel.getCategories(), BrowseModel.getCatName(), ImagesModel.getImageInfo(), IndexModel.getLatestPictures(), TagModel.getPics(), BrowseModel.getPictures(), Galleria_Model_Collection.getSearchPictures(), IndexModel.getStats(), Galleria_Model_Collection.getTags(), ProfileController.indexAction(), Galleria_View_Tags.lists(), JsonModel.pictureVisibility(), and JsonController.postAction().
static Galleria_Auth.logOut () [static]
Logs out.
This function logs out by deleting auth object from session. public
Definition at line 76 of file auth.php.
References Galleria_Session.del().
Referenced by LoginController.outAction().
static Galleria_Auth.init () [static]
Initialize auth object.
This function gets new information for auth object and updates it. public
Definition at line 88 of file auth.php.
References Galleria_Session.set().
The documentation for this class was generated from the following file:
/var/www/galleria/data/lib/auth.php