Kuvagalleria: AdminModel Class Reference
AdminModel Class Reference
Public Member Functions
getGroups ()
getUsers ()
addNewUser ($name, $user, $pass)
addNewGroup ($name, $admin)
addPicture ($pg, $year, $desc)
getPics ()
Detailed Description
Definition at line 19 of file adminmodel.php.
Member Function Documentation
AdminModel.getGroups ()
Give groups.
This function returns groups. public
Returns:
array
Reimplemented from Galleria_Model_Collection.
Definition at line 29 of file adminmodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
AdminModel.getUsers ()
Give users.
This function returns users. public
Returns:
array
Definition at line 44 of file adminmodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
AdminModel.addNewUser ($ name, $ user, $ pass)
Add new user.
This function adds new user. public
Parameters:
string $name
string $user
string $pass
Returns:
stdClass
Definition at line 62 of file adminmodel.php.
References Galleria_Model._getConnection().
AdminModel.addNewGroup ($ name, $ admin)
Add new group.
This function adds new group. public
Parameters:
string $name
boolean $admin
Returns:
stdClass
Definition at line 79 of file adminmodel.php.
References Galleria_Model._getConnection().
AdminModel.addPicture ($ pg, $ year, $ desc)
Add new picture.
This function add new picture. public
Parameters:
string $pg
string $year
string $desc
Returns:
boolean
Definition at line 100 of file adminmodel.php.
References Galleria_Model_Collection._addChangelog(), Galleria_Model._getConnection(), and Galleria_Auth.getObject().
AdminModel.getPics ()
Give pictures.
This function returns pictures, which are not in a group nor shown. public
Returns:
array
Definition at line 114 of file adminmodel.php.
References Galleria_Model._fetchObjects(), and Galleria_Model._getConnection().
The documentation for this class was generated from the following file:
/var/www/galleria/data/site/mvc/model/adminmodel.php