<?php
/**
 * Documentation
 */

if ($view->failed) {
    echo '<p>Login failed.</p>';
}

if ($view->show_form): ?>
<form action="" method="post">
    <p>
        <label for="username">Username</label>
        <input id="username" name="username" type="text" />
    </p>
    <p>
        <label for="password">Password</label>
        <input id="password" name="password" type="password" />
    </p>
    <p><input type="submit" value="Log in" /></p>
</form>
<?php else: ?>
<p>Logged in</p>
<?php endif; ?>
